/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cv.marco;
import javax.swing.*;
import java.awt.BorderLayout;


/**
 *
 * @author Marco
 */
public class mainscreen extends javax.swing.JPanel {
           JFrame newFrame = new JFrame();
          
            String personalia = ("<html>Naam:               Marco van Wijk<br>" +
"Adres:          Herenstraat 4<br>" +
"Postcode/plaats:			1506 DL Zaandam<br>" +
"Geboortedatum:			18-06-1989<br>" +
"Geboorteplaats:			Zaanstad<br>" +
"Mobiele telefoon:			0657589858<br>" +
"E-mailadres:				seocialise1@gmail.com</html>");
        
        String Opleiding = ("<html>09/2012 – 06/2014<br>" +
                                        "MBO Verkoopspecialist<br>" +
"					ROC Sloterdijk, Amsterdam<br>" +
"					Diploma behaald<br>" +
"<br>" +
"09/2005 – 01/2007<br>" +
                                        "MBO Bank en Verzekeringswezen<br>" +
"					Horizon College, Hoorn<br>" +
"					Niet afgerond<br>" +
"<br>" +
"08/2001 – 06/2005<br>" +
                                        "VMBO-kb<br>" +
"					Zaanlands West, Zaandam<br>" +
"					Richting administratie met eindexamenvakken: <br>" + 						
                "Nederlands, Engels, wiskunde, economie, administratie<br>" +
"					Diploma behaald</html>");
        
        String Werkervaring = ("<html>06/2011 – heden<br>" +			
                "Verkoopmedewerker C&A Nederland<br>" +
"                               	C&A Amstelveen<br>" +
"					Referentie op aanvraag <br>" +
"<br>" +
"06/2008 – heden	<br>" +
                "Freelance internetmarketeer <br>" +
"					<br>" +
"<br>" +
"07/2007 – 00/2009<br>" +
                "Magazijnmedewerker all-round<br>" +
"					Ahold, Zaandam</html>");
        
        String Vaardigheden = ("<html>* Opzetten en managen van campagnes met affiliate netwerken;<br>" +
"* Bedenken, opzetten en uitvoeren van online campagnes;<br>" +
"* Analyseren en bijsturen van campagnes;<br>" +
"* Google Webmaster Tools<br>" +
"* Google Analytics<br>" +
"* On-page SEO (o.a. aanpassen van meta-tags, title-tags, headers) <br>" +
"* Off-page SEO (o.a. Linkbuilding, opzetten en bijhouden van social networkpages)<br>" +
"* Article marketing<br>" +
"* E-mail marketing<br>" +
"* Opbouwen van targeted e-mail lists<br>" +
"* Implementeren van eenvoudige scripts<br>" +
"* Omgevingen: Intranet, Windows 2000/XP/Vista/10, Microsoft Office </html>");
        
        String Aanvullend = ("<html>Beheersing Nederlandse taal:		Goed<br>" +
"Beheersing Engelse taal:		Goed</html>");
    /**
     * Creates new form mainscreen
     */
    public mainscreen() {
        initComponents();
        newFrame.getContentPane().add(this, BorderLayout.CENTER);
        newFrame.setDefaultCloseOperation(Window­Constants.EXIT_ON_CLOSE);
        newFrame.pack();
        newFrame.setVisible(true);
        newFrame.setTitle("Curriculum Vitae Marco van Wijk");
        
        jButton1.setText ("Personalia");
        jButton2.setText ("Opleiding");
        jButton3.setText ("Werkervaring");
        jButton4.setText ("Vaardigheden");
        jButton5.setText ("Aanvullende informatie");
        
       
       // jLabel2.setText (Opleiding + "");
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jButton6.setText("jButton6");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Curriculum Vitae van Marco van Wijk");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabel2.setText (personalia + "");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel2.setText (Opleiding + "");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel2.setText (Werkervaring + "");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jLabel2.setText (Vaardigheden + "");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jLabel2.setText (Aanvullend + "");
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
